<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('banks')->insertOrIgnore([
            ["name" => 'ABHYUDAYA COOPERATIVE BANK LIMITED'],
            ["name" => 'THE ROYAL BANK OF SCOTLAND N V'],
            ["name" => 'ABU DHABI COMMERCIAL BANK'],
            ["name" => 'AKOLA JANATA COMMERCIAL COOPERATIVE BANK'],
            ["name" => 'ALLAHABAD BANK'],
            ["name" => 'AHMEDABAD MERCANTILE COOPERATIVE BANK'],
            ["name" => 'ANDHRA BANK'],
            ["name" => 'AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED'],
            ["name" => 'THE ANDHRA PRADESH STATE COOPERATIVE BANK LIMITED'],
            ["name" => 'ANDHRA PRAGATHI GRAMEENA BANK'],
            ["name" => 'THE A.P. MAHESH COOPERATIVE URBAN BANK LIMITED'],
            ["name" => 'APNA SAHAKARI BANK LIMITED'],
            ["name" => 'ALMORA URBAN COOPERATIVE BANK LIMITED'],
            ["name" => 'BASSEIN CATHOLIC COOPERATIVE BANK LIMITED'],
            ["name" => 'BANK OF BARODA'],
            ["name" => 'BARCLAYS BANK'],
            ["name" => 'BANK OF BAHARAIN AND KUWAIT BSC'],
            ["name" => 'BHARAT COOPERATIVE BANK MUMBAI LIMITED'],
            ["name" => 'BANK OF CEYLON'],
            ["name" => 'BANDHAN BANK LIMITED'],
            ["name" => 'DENA BANK'],
            ["name" => 'BANK OF INDIA'],
            ["name" => 'BHARATIYA MAHILA BANK LIMITED'],
            ["name" => 'B N P PARIBAS'],
            ["name" => 'BANK OF AMERICA'],
            ["name" => 'BANK OF TOKYO MITSUBISHI LIMITED'],
            ["name" => 'CENTRAL BANK OF INDIA'],
            ["name" => 'CITIZEN CREDIT COOPERATIVE BANK LIMITED'],
            ["name" => 'JP MORGAN BANK'],
            ["name" => 'CITI BANK'],
            ["name" => 'CITY UNION BANK LIMITED'],
            ["name" => 'CAPITAL LOCAL AREA BANK LIMITED'],
            ["name" => 'CANARA BANK'],
            ["name" => 'CORPORATION BANK'],
            ["name" => 'THE COSMOS CO OPERATIVE BANK LIMITED'],
            ["name" => 'CREDIT SUISEE AG'],
            ["name" => 'CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK CAL'],
            ["name" => 'SHRI CHHATRAPATI RAJASHRI SHAHU URBAN COOPERATIVE'],
            ["name" => 'CATHOLIC SYRIAN BANK LIMITED'],
            ["name" => 'COMMONWEALTH BANK OF AUSTRALIA'],
            ["name" => 'CHINATRUST COMMERCIAL BANK LIMITED'],
            ["name" => 'DEVELOPMENT BANK OF SINGAPORE'],
            ["name" => 'DCB BANK LIMITED'],
            ["name" => 'DEUSTCHE BANK'],
            ["name" => 'DEPOSIT INSURANCE AND CREDIT GUARANTEE CORPORATIO'],
            ["name" => 'THE DELHI STATE COOPERATIVE BANK LIMITED'],
            ["name" => 'DHANALAKSHMI BANK'],
            ["name" => 'DOMBIVLI NAGARI SAHAKARI BANK LIMITED'],
            ["name" => 'DOHA BANK QSC'],
            ["name" => 'DOHA BANK'],
            ["name" => 'EXPORT IMPORT BANK OF INDIA'],
            ["name" => 'FEDERAL BANK'],
            ["name" => 'FIRSTRAND BANK LIMITED'],
            ["name" => 'THE GREATER BOMBAY COOPERATIVE BANK LIMITED'],
            ["name" => 'THE GADCHIROLI DISTRICT CENTRAL COOPERATIVE BANK '],
            ["name" => 'THE GUJARAT STATE COOPERATIVE BANK LIMITED'],
            ["name" => 'THE HASTI COOP BANK LTD'],
            ["name" => 'HDFC BANK'],
            ["name" => 'HSBC BANK'],
            ["name" => 'WOORI BANK'],
            ["name" => 'BANK INTERNASIONAL INDONESIA'],
            ["name" => 'IDBI BANK'],
            ["name" => 'INDUSTRIAL BANK OF KOREA'],
            ["name" => 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED'],
            ["name" => 'ICICI BANK LIMITED'],
            ["name" => 'IDFC BANK LIMITED'],
            ["name" => 'INDIAN BANK'],
            ["name" => 'INDUSIND BANK'],
            ["name" => 'INDIAN OVERSEAS BANK'],
            ["name" => 'JAMMU AND KASHMIR BANK LIMITED'],
            ["name" => 'JANASEVA SAHAKARI BANK LIMITED'],
            ["name" => 'JANASEVA SAHAKARI BANK BORIVLI LIMITED'],
            ["name" => 'JALGAON JANATA SAHAKARI BANK LIMITED'],
            ["name" => 'THE JALGAON PEOPELS COOPERATIVE BANK LIMITED'],
            ["name" => 'JANAKALYAN SAHAKARI BANK LIMITED'],
            ["name" => 'JANATA SAHAKARI BANK LIMITED'],
            ["name" => 'THE KANGRA CENTRAL COOPERATIVE BANK LIMITED'],
            ["name" => 'KALLAPPANNA AWADE ICHALKARANJI JANATA SAHAKARI BA'],
            ["name" => 'THE KANGRA COOPERATIVE BANK LIMITED'],
            ["name" => 'KARNATAKA BANK LIMITED'],
            ["name" => 'KAPOL COOPERATIVE BANK LIMITED'],
            ["name" => 'KALUPUR COMMERCIAL COOPERATIVE BANK'],
            ["name" => 'KALYAN JANATA SAHAKARI BANK'],
            ["name" => 'KOTAK MAHINDRA BANK LIMITED'],
            ["name" => 'KERALA GRAMIN BANK'],
            ["name" => 'THE KURMANCHAL NAGAR SAHAKARI BANK LIMITED'],
            ["name" => 'THE KARANATAKA STATE COOPERATIVE APEX BANK LIMITE'],
            ["name" => 'THE KARAD URBAN COOPERATIVE BANK LIMITED'],
            ["name" => 'KARUR VYSYA BANK'],
            ["name" => 'KARNATAKA VIKAS GRAMEENA BANK'],
            ["name" => 'LAXMI VILAS BANK'],
            ["name" => 'BANK OF MAHARASHTRA'],
            ["name" => 'MAHANAGAR COOPERATIVE BANK'],
            ["name" => 'THE MUMBAI DISTRICT CENTRAL COOPERATIVE BANK LIMI'],
            ["name" => 'MIZUHO CORPORATE BANK LIMITED'],
            ["name" => 'MAHARASHTRA STATE COOPERATIVE BANK'],
            ["name" => 'MASHREQBANK PSC'],
            ["name" => 'THE MEHSANA URBAN COOPERATIVE BANK'],
            ["name" => 'THE MUNICIPAL COOPERATIVE BANK LIMITED'],
            ["name" => 'NATIONAL AUSTRALIA BANK LIMITED'],
            ["name" => 'NATIONAL BANK OF ABU DHABI PJSC'],
            ["name" => 'NAGPUR NAGARIK SAHAKARI BANK LIMITED'],
            ["name" => 'NEW INDIA COOPERATIVE BANK LIMITED'],
            ["name" => 'NKGSB COOPERATIVE BANK LIMITED'],
            ["name" => 'THE NASIK MERCHANTS COOPERATIVE BANK LIMITED'],
            ["name" => 'NUTAN NAGARIK SAHAKARI BANK LIMITED'],
            ["name" => 'THE BANK OF NOVA SCOTIA'],
            ["name" => 'THE NAINITAL BANK LIMITED'],
            ["name" => 'NAGAR URBAN CO OPERATIVE BANK'],
            ["name" => 'ORIENTAL BANK OF COMMERCE'],
            ["name" => 'G P PARSIK BANK'],
            ["name" => 'PRAGATHI KRISHNA GRAMIN BANK'],
            ["name" => 'PUNJAB AND MAHARSHTRA COOPERATIVE BANK'],
            ["name" => 'PRATHAMA BANK'],
            ["name" => 'PUNJAB NATIONAL BANK'],
            ["name" => 'RABOBANK INTERNATIONAL'],
            ["name" => 'RATNAKAR BANK LIMITED'],
            ["name" => 'RESERVE BANK OF INDIA'],
            ["name" => 'RAJKOT NAGRIK SAHAKARI BANK LIMITED'],
            ["name" => 'RAJGURUNAGAR SAHAKARI BANK LIMITED'],
            ["name" => 'THE RAJASTHAN STATE COOPERATIVE BANK LIMITED'],
            ["name" => 'SBER BANK'],
            ["name" => 'SAHEBRAO DESHMUKH COOPERATIVE BANK LIMITED'],
            ["name" => 'STATE BANK OF BIKANER AND JAIPUR'],
            ["name" => 'STATE BANK OF HYDERABAD'],
            ["name" => 'STATE BANK OF INDIA'],
            ["name" => 'STATE BANK OF MYSORE'],
            ["name" => 'STATE BANK OF TRAVANCORE'],
            ["name" => 'STANDARD CHARTERED BANK'],
            ["name" => 'THE SURAT DISTRICT COOPERATIVE BANK LIMITED'],
            ["name" => 'SHINHAN BANK'],
            ["name" => 'SOUTH INDIAN BANK'],
            ["name" => 'SOLAPUR JANATA SAHAKARI BANK LIMITED'],
            ["name" => 'SHIKSHAK SAHAKARI BANK LIMITED'],
            ["name" => 'SUMITOMO MITSUI BANKING CORPORATION'],
            ["name" => 'SOCIETE GENERALE'],
            ["name" => 'THE SURATH PEOPLES COOPERATIVE BANK LIMITED'],
            ["name" => 'SARASWAT COOPERATIVE BANK LIMITED'],
            ["name" => 'STATE BANK OF PATIALA'],
            ["name" => 'SBM BANK MAURITIUS LIMITED'],
            ["name" => 'SURAT NATIONAL COOPERATIVE BANK LIMITED'],
            ["name" => 'THE SHAMRAO VITHAL COOPERATIVE BANK'],
            ["name" => 'SYNDICATE BANK'],
            ["name" => 'THE THANE BHARAT SAHAKARI BANK LIMITED'],
            ["name" => 'TUMKUR GRAIN MERCHANTS COOPERATIVE BANK LIMITED'],
            ["name" => 'TJSB SAHAKARI BANK LTD'],
            ["name" => 'TAMILNAD MERCANTILE BANK LIMITED'],
            ["name" => 'THE TAMIL NADU STATE APEX COOPERATIVE BANK'],
            ["name" => 'UNITED BANK OF INDIA'],
            ["name" => 'AXIS BANK'],
            ["name" => 'THE VARACHHA COOPERATIVE BANK LIMITED'],
            ["name" => 'VIJAYA BANK'],
            ["name" => 'THE VISHWESHWAR SAHAKARI BANK LIMITED'],
            ["name" => 'VASAI VIKAS SAHAKARI BANK LIMITED'],
            ["name" => 'ING VYSYA BANK'],
            ["name" => 'THE WEST BENGAL STATE COOPERATIVE BANK'],
            ["name" => 'WESTPAC BANKING CORPORATION'],
            ["name" => 'YES BANK'],
            ["name" => 'THE ZOROASTRIAN COOPERATIVE BANK LIMITED'],
            ["name" => 'ZILA SAHAKRI BANK LIMITED GHAZIABAD']
        ]);
    }
}
