<?php

use Illuminate\Database\Seeder;

class StateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('states')->insertOrIgnore([
            ['id'=>245, 'name'=>'Auckland', 'country_id'=>13],
            ['id'=>246, 'name'=>'Australian Capital Territory', 'country_id'=>13],
            ['id'=>247, 'name'=>'Balgowlah', 'country_id'=>13],
            ['id'=>248, 'name'=>'Balmain', 'country_id'=>13],
            ['id'=>249, 'name'=>'Bankstown', 'country_id'=>13],
            ['id'=>250, 'name'=>'Baulkham Hills', 'country_id'=>13],
            ['id'=>251, 'name'=>'Bonnet Bay', 'country_id'=>13],
            ['id'=>252, 'name'=>'Camberwell', 'country_id'=>13],
            ['id'=>253, 'name'=>'Carole Park', 'country_id'=>13],
            ['id'=>254, 'name'=>'Castle Hill', 'country_id'=>13],
            ['id'=>255, 'name'=>'Caulfield', 'country_id'=>13],
            ['id'=>256, 'name'=>'Chatswood', 'country_id'=>13],
            ['id'=>257, 'name'=>'Cheltenham', 'country_id'=>13],
            ['id'=>258, 'name'=>'Cherrybrook', 'country_id'=>13],
            ['id'=>259, 'name'=>'Clayton', 'country_id'=>13],
            ['id'=>260, 'name'=>'Collingwood', 'country_id'=>13],
            ['id'=>261, 'name'=>'Frenchs Forest', 'country_id'=>13],
            ['id'=>262, 'name'=>'Hawthorn', 'country_id'=>13],
            ['id'=>263, 'name'=>'Jannnali', 'country_id'=>13],
            ['id'=>264, 'name'=>'Knoxfield', 'country_id'=>13],
            ['id'=>265, 'name'=>'Melbourne', 'country_id'=>13],
            ['id'=>266, 'name'=>'New South Wales', 'country_id'=>13],
            ['id'=>267, 'name'=>'Northern Territory', 'country_id'=>13],
            ['id'=>268, 'name'=>'Perth', 'country_id'=>13],
            ['id'=>269, 'name'=>'Queensland', 'country_id'=>13],
            ['id'=>270, 'name'=>'South Australia', 'country_id'=>13],
            ['id'=>271, 'name'=>'Tasmania', 'country_id'=>13],
            ['id'=>272, 'name'=>'Templestowe', 'country_id'=>13],
            ['id'=>273, 'name'=>'Victoria', 'country_id'=>13],
            ['id'=>274, 'name'=>'Werribee south', 'country_id'=>13],
            ['id'=>275, 'name'=>'Western Australia', 'country_id'=>13],
            ['id'=>276, 'name'=>'Wheeler', 'country_id'=>13],

            ['id'=>1, 'name'=>'Andaman and Nicobar Islands', 'country_id'=>101],
            ['id'=>2, 'name'=>'Andhra Pradesh', 'country_id'=>101],
            ['id'=>3, 'name'=>'Arunachal Pradesh', 'country_id'=>101],
            ['id'=>4, 'name'=>'Assam', 'country_id'=>101],
            ['id'=>5, 'name'=>'Bihar', 'country_id'=>101],
            ['id'=>6, 'name'=>'Chandigarh', 'country_id'=>101],
            ['id'=>7, 'name'=>'Chhattisgarh', 'country_id'=>101],
            ['id'=>8, 'name'=>'Dadra and Nagar Haveli', 'country_id'=>101],
            ['id'=>9, 'name'=>'Daman and Diu', 'country_id'=>101],
            ['id'=>10, 'name'=>'Delhi', 'country_id'=>101],
            ['id'=>11, 'name'=>'Goa', 'country_id'=>101],
            ['id'=>12, 'name'=>'Gujarat', 'country_id'=>101],
            ['id'=>13, 'name'=>'Haryana', 'country_id'=>101],
            ['id'=>14, 'name'=>'Himachal Pradesh', 'country_id'=>101],
            ['id'=>15, 'name'=>'Jammu and Kashmir', 'country_id'=>101],
            ['id'=>16, 'name'=>'Jharkhand', 'country_id'=>101],
            ['id'=>17, 'name'=>'Karnataka', 'country_id'=>101],
            ['id'=>18, 'name'=>'Kenmore', 'country_id'=>101],
            ['id'=>19, 'name'=>'Kerala', 'country_id'=>101],
            ['id'=>20, 'name'=>'Lakshadweep', 'country_id'=>101],
            ['id'=>21, 'name'=>'Madhya Pradesh', 'country_id'=>101],
            ['id'=>22, 'name'=>'Maharashtra', 'country_id'=>101],
            ['id'=>23, 'name'=>'Manipur', 'country_id'=>101],
            ['id'=>24, 'name'=>'Meghalaya', 'country_id'=>101],
            ['id'=>25, 'name'=>'Mizoram', 'country_id'=>101],
            ['id'=>26, 'name'=>'Nagaland', 'country_id'=>101],
            ['id'=>27, 'name'=>'Narora', 'country_id'=>101],
            ['id'=>28, 'name'=>'Natwar', 'country_id'=>101],
            ['id'=>29, 'name'=>'Odisha', 'country_id'=>101],
            ['id'=>30, 'name'=>'Paschim Medinipur', 'country_id'=>101],
            ['id'=>31, 'name'=>'Pondicherry', 'country_id'=>101],
            ['id'=>32, 'name'=>'Punjab', 'country_id'=>101],
            ['id'=>33, 'name'=>'Rajasthan', 'country_id'=>101],
            ['id'=>34, 'name'=>'Sikkim', 'country_id'=>101],
            ['id'=>35, 'name'=>'Tamil Nadu', 'country_id'=>101],
            ['id'=>36, 'name'=>'Telangana', 'country_id'=>101],
            ['id'=>37, 'name'=>'Tripura', 'country_id'=>101],
            ['id'=>38, 'name'=>'Uttar Pradesh', 'country_id'=>101],
            ['id'=>39, 'name'=>'Uttarakhand', 'country_id'=>101],
            ['id'=>40, 'name'=>'Vaishali', 'country_id'=>101],
            ['id'=>41, 'name'=>'West Bengal', 'country_id'=>101],

            ['id'=>2307, "name"=>'Johor', 'country_id'=>132],
            ['id'=>2308, "name"=>'Kedah', 'country_id'=>132],
            ['id'=>2309, "name"=>'Kelantan', 'country_id'=>132],
            ['id'=>2310, "name"=>'Kuala Lumpur', 'country_id'=>132],
            ['id'=>2311, "name"=>'Labuan', 'country_id'=>132],
            ['id'=>2312, "name"=>'Melaka', 'country_id'=>132],
            ['id'=>2313, "name"=>'Negeri Johor', 'country_id'=>132],
            ['id'=>2314, "name"=>'Negeri Sembilan', 'country_id'=>132],
            ['id'=>2315, "name"=>'Pahang', 'country_id'=>132],
            ['id'=>2316, "name"=>'Penang', 'country_id'=>132],
            ['id'=>2317, "name"=>'Perak', 'country_id'=>132],
            ['id'=>2318, "name"=>'Perlis', 'country_id'=>132],
            ['id'=>2319, "name"=>'Pulau Pinang', 'country_id'=>132],
            ['id'=>2320, "name"=>'Sabah', 'country_id'=>132],
            ['id'=>2321, "name"=>'Sarawak', 'country_id'=>132],
            ['id'=>2322, "name"=>'Selangor', 'country_id'=>132],
            ['id'=>2323, "name"=>'Sembilan', 'country_id'=>132],
            ['id'=>2324, "name"=>'Terengganu', 'country_id'=>132],

            ['id'=>2603, "name"=>'Area Outside Region', 'country_id'=>157],
            ['id'=>2604, "name"=>'Auckland', 'country_id'=>157],
            ['id'=>2605, "name"=>'Bay of Plenty', 'country_id'=>157],
            ['id'=>2606, "name"=>'Canterbury', 'country_id'=>157],
            ['id'=>2607, "name"=>'Christchurch', 'country_id'=>157],
            ['id'=>2608, "name"=>'Gisborne', 'country_id'=>157],
            ['id'=>2609, "name"=>"Hawke''s Bay", 'country_id'=>157],
            ['id'=>2610, "name"=>'Manawatu-Wanganui', 'country_id'=>157],
            ['id'=>2611, "name"=>'Marlborough', 'country_id'=>157],
            ['id'=>2612, "name"=>'Nelson', 'country_id'=>157],
            ['id'=>2613, "name"=>'Northland', 'country_id'=>157],
            ['id'=>2614, "name"=>'Otago', 'country_id'=>157],
            ['id'=>2615, "name"=>'Rodney', 'country_id'=>157],
            ['id'=>2616, "name"=>'Southland', 'country_id'=>157],
            ['id'=>2617, "name"=>'Taranaki', 'country_id'=>157],
            ['id'=>2618, "name"=>'Tasman', 'country_id'=>157],
            ['id'=>2619, "name"=>'Waikato', 'country_id'=>157],
            ['id'=>2620, "name"=>'Wellington', 'country_id'=>157],
            ['id'=>2621, "name"=>'West Coast', 'country_id'=>157],

            ['id'=>3186, "name"=>'Singapore', 'country_id'=>196],

            ['id'=>3805, "name"=>'Aberdeen', 'country_id'=>230],
            ['id'=>3806, "name"=>'Aberdeenshire', 'country_id'=>230],
            ['id'=>3807, "name"=>'Argyll', 'country_id'=>230],
            ['id'=>3808, "name"=>'Armagh', 'country_id'=>230],
            ['id'=>3809, "name"=>'Bedfordshire', 'country_id'=>230],
            ['id'=>3810, "name"=>'Belfast', 'country_id'=>230],
            ['id'=>3811, "name"=>'Berkshire', 'country_id'=>230],
            ['id'=>3812, "name"=>'Birmingham', 'country_id'=>230],
            ['id'=>3813, "name"=>'Brechin', 'country_id'=>230],
            ['id'=>3814, "name"=>'Bridgnorth', 'country_id'=>230],
            ['id'=>3815, "name"=>'Bristol', 'country_id'=>230],
            ['id'=>3816, "name"=>'Buckinghamshire', 'country_id'=>230],
            ['id'=>3817, "name"=>'Cambridge', 'country_id'=>230],
            ['id'=>3818, "name"=>'Cambridgeshire', 'country_id'=>230],
            ['id'=>3819, "name"=>'Channel Islands', 'country_id'=>230],
            ['id'=>3820, "name"=>'Cheshire', 'country_id'=>230],
            ['id'=>3821, "name"=>'Cleveland', 'country_id'=>230],
            ['id'=>3822, "name"=>'Co Fermanagh', 'country_id'=>230],
            ['id'=>3823, "name"=>'Conwy', 'country_id'=>230],
            ['id'=>3824, "name"=>'Cornwall', 'country_id'=>230],
            ['id'=>3825, "name"=>'Coventry', 'country_id'=>230],
            ['id'=>3826, "name"=>'Craven Arms', 'country_id'=>230],
            ['id'=>3827, "name"=>'Cumbria', 'country_id'=>230],
            ['id'=>3828, "name"=>'Denbighshire', 'country_id'=>230],
            ['id'=>3829, "name"=>'Derby', 'country_id'=>230],
            ['id'=>3830, "name"=>'Derbyshire', 'country_id'=>230],
            ['id'=>3831, "name"=>'Devon', 'country_id'=>230],
            ['id'=>3832, "name"=>'Dial Code Dungannon', 'country_id'=>230],
            ['id'=>3833, "name"=>'Didcot', 'country_id'=>230],
            ['id'=>3834, "name"=>'Dorset', 'country_id'=>230],
            ['id'=>3835, "name"=>'Dunbartonshire', 'country_id'=>230],
            ['id'=>3836, "name"=>'Durham', 'country_id'=>230],
            ['id'=>3837, "name"=>'East Dunbartonshire', 'country_id'=>230],
            ['id'=>3838, "name"=>'East Lothian', 'country_id'=>230],
            ['id'=>3839, "name"=>'East Midlands', 'country_id'=>230],
            ['id'=>3840, "name"=>'East Sussex', 'country_id'=>230],
            ['id'=>3841, "name"=>'East Yorkshire', 'country_id'=>230],
            ['id'=>3842, "name"=>'England', 'country_id'=>230],
            ['id'=>3843, "name"=>'Essex', 'country_id'=>230],
            ['id'=>3844, "name"=>'Fermanagh', 'country_id'=>230],
            ['id'=>3845, "name"=>'Fife', 'country_id'=>230],
            ['id'=>3846, "name"=>'Flintshire', 'country_id'=>230],
            ['id'=>3847, "name"=>'Fulham', 'country_id'=>230],
            ['id'=>3848, "name"=>'Gainsborough', 'country_id'=>230],
            ['id'=>3849, "name"=>'Glocestershire', 'country_id'=>230],
            ['id'=>3850, "name"=>'Gwent', 'country_id'=>230],
            ['id'=>3851, "name"=>'Hampshire', 'country_id'=>230],
            ['id'=>3852, "name"=>'Hants', 'country_id'=>230],
            ['id'=>3853, "name"=>'Herefordshire', 'country_id'=>230],
            ['id'=>3854, "name"=>'Hertfordshire', 'country_id'=>230],
            ['id'=>3855, "name"=>'Ireland', 'country_id'=>230],
            ['id'=>3856, "name"=>'Isle Of Man', 'country_id'=>230],
            ['id'=>3857, "name"=>'Isle of Wight', 'country_id'=>230],
            ['id'=>3858, "name"=>'Kenford', 'country_id'=>230],
            ['id'=>3859, "name"=>'Kent', 'country_id'=>230],
            ['id'=>3860, "name"=>'Kilmarnock', 'country_id'=>230],
            ['id'=>3861, "name"=>'Lanarkshire', 'country_id'=>230],
            ['id'=>3862, "name"=>'Lancashire', 'country_id'=>230],
            ['id'=>3863, "name"=>'Leicestershire', 'country_id'=>230],
            ['id'=>3864, "name"=>'Lincolnshire', 'country_id'=>230],
            ['id'=>3865, "name"=>'Llanymynech', 'country_id'=>230],
            ['id'=>3866, "name"=>'London', 'country_id'=>230],
            ['id'=>3867, "name"=>'Ludlow', 'country_id'=>230],
            ['id'=>3868, "name"=>'Manchester', 'country_id'=>230],
            ['id'=>3869, "name"=>'Mayfair', 'country_id'=>230],
            ['id'=>3870, "name"=>'Merseyside', 'country_id'=>230],
            ['id'=>3871, "name"=>'Mid Glamorgan', 'country_id'=>230],
            ['id'=>3872, "name"=>'Middlesex', 'country_id'=>230],
            ['id'=>3873, "name"=>'Mildenhall', 'country_id'=>230],
            ['id'=>3874, "name"=>'Monmouthshire', 'country_id'=>230],
            ['id'=>3875, "name"=>'Newton Stewart', 'country_id'=>230],
            ['id'=>3876, "name"=>'Norfolk', 'country_id'=>230],
            ['id'=>3877, "name"=>'North Humberside', 'country_id'=>230],
            ['id'=>3878, "name"=>'North Yorkshire', 'country_id'=>230],
            ['id'=>3879, "name"=>'Northamptonshire', 'country_id'=>230],
            ['id'=>3880, "name"=>'Northants', 'country_id'=>230],
            ['id'=>3881, "name"=>'Northern Ireland', 'country_id'=>230],
            ['id'=>3882, "name"=>'Northumberland', 'country_id'=>230],
            ['id'=>3883, "name"=>'Nottinghamshire', 'country_id'=>230],
            ['id'=>3884, "name"=>'Oxford', 'country_id'=>230],
            ['id'=>3885, "name"=>'Powys', 'country_id'=>230],
            ['id'=>3886, "name"=>'Roos-shire', 'country_id'=>230],
            ['id'=>3887, "name"=>'SUSSEX', 'country_id'=>230],
            ['id'=>3888, "name"=>'Sark', 'country_id'=>230],
            ['id'=>3889, "name"=>'Scotland', 'country_id'=>230],
            ['id'=>3890, "name"=>'Scottish Borders', 'country_id'=>230],
            ['id'=>3891, "name"=>'Shropshire', 'country_id'=>230],
            ['id'=>3892, "name"=>'Somerset', 'country_id'=>230],
            ['id'=>3893, "name"=>'South Glamorgan', 'country_id'=>230],
            ['id'=>3894, "name"=>'South Wales', 'country_id'=>230],
            ['id'=>3895, "name"=>'South Yorkshire', 'country_id'=>230],
            ['id'=>3896, "name"=>'Southwell', 'country_id'=>230],
            ['id'=>3897, "name"=>'Staffordshire', 'country_id'=>230],
            ['id'=>3898, "name"=>'Strabane', 'country_id'=>230],
            ['id'=>3899, "name"=>'Suffolk', 'country_id'=>230],
            ['id'=>3900, "name"=>'Surrey', 'country_id'=>230],
            ['id'=>3901, "name"=>'Sussex', 'country_id'=>230],
            ['id'=>3902, "name"=>'Twickenham', 'country_id'=>230],
            ['id'=>3903, "name"=>'Tyne and Wear', 'country_id'=>230],
            ['id'=>3904, "name"=>'Tyrone', 'country_id'=>230],
            ['id'=>3905, "name"=>'Utah', 'country_id'=>230],
            ['id'=>3906, "name"=>'Wales', 'country_id'=>230],
            ['id'=>3907, "name"=>'Warwickshire', 'country_id'=>230],
            ['id'=>3908, "name"=>'West Lothian', 'country_id'=>230],
            ['id'=>3909, "name"=>'West Midlands', 'country_id'=>230],
            ['id'=>3910, "name"=>'West Sussex', 'country_id'=>230],
            ['id'=>3911, "name"=>'West Yorkshire', 'country_id'=>230],
            ['id'=>3912, "name"=>'Whissendine', 'country_id'=>230],
            ['id'=>3913, "name"=>'Wiltshire', 'country_id'=>230],
            ['id'=>3914, "name"=>'Wokingham', 'country_id'=>230],
            ['id'=>3915, "name"=>'Worcestershire', 'country_id'=>230],
            ['id'=>3916, "name"=>'Wrexham', 'country_id'=>230],
            ['id'=>3917, "name"=>'Wurttemberg', 'country_id'=>230],
            ['id'=>3918, "name"=>'Yorkshire', 'country_id'=>230],

            ['id'=>3919, "name"=>'Alabama', 'country_id'=>231],
            ['id'=>3920, "name"=>'Alaska', 'country_id'=>231],
            ['id'=>3921, "name"=>'Arizona', 'country_id'=>231],
            ['id'=>3922, "name"=>'Arkansas', 'country_id'=>231],
            ['id'=>3923, "name"=>'Byram', 'country_id'=>231],
            ['id'=>3924, "name"=>'California', 'country_id'=>231],
            ['id'=>3925, "name"=>'Cokato', 'country_id'=>231],
            ['id'=>3926, "name"=>'Colorado', 'country_id'=>231],
            ['id'=>3927, "name"=>'Connecticut', 'country_id'=>231],
            ['id'=>3928, "name"=>'Delaware', 'country_id'=>231],
            ['id'=>3929, "name"=>'District of Columbia', 'country_id'=>231],
            ['id'=>3930, "name"=>'Florida', 'country_id'=>231],
            ['id'=>3931, "name"=>'Georgia', 'country_id'=>231],
            ['id'=>3932, "name"=>'Hawaii', 'country_id'=>231],
            ['id'=>3933, "name"=>'Idaho', 'country_id'=>231],
            ['id'=>3934, "name"=>'Illinois', 'country_id'=>231],
            ['id'=>3935, "name"=>'Indiana', 'country_id'=>231],
            ['id'=>3936, "name"=>'Iowa', 'country_id'=>231],
            ['id'=>3937, "name"=>'Kansas', 'country_id'=>231],
            ['id'=>3938, "name"=>'Kentucky', 'country_id'=>231],
            ['id'=>3939, "name"=>'Louisiana', 'country_id'=>231],
            ['id'=>3940, "name"=>'Lowa', 'country_id'=>231],
            ['id'=>3941, "name"=>'Maine', 'country_id'=>231],
            ['id'=>3942, "name"=>'Maryland', 'country_id'=>231],
            ['id'=>3943, "name"=>'Massachusetts', 'country_id'=>231],
            ['id'=>3944, "name"=>'Medfield', 'country_id'=>231],
            ['id'=>3945, "name"=>'Michigan', 'country_id'=>231],
            ['id'=>3946, "name"=>'Minnesota', 'country_id'=>231],
            ['id'=>3947, "name"=>'Mississippi', 'country_id'=>231],
            ['id'=>3948, "name"=>'Missouri', 'country_id'=>231],
            ['id'=>3949, "name"=>'Montana', 'country_id'=>231],
            ['id'=>3950, "name"=>'Nebraska', 'country_id'=>231],
            ['id'=>3951, "name"=>'Nevada', 'country_id'=>231],
            ['id'=>3952, "name"=>'New Hampshire', 'country_id'=>231],
            ['id'=>3953, "name"=>'New Jersey', 'country_id'=>231],
            ['id'=>3954, "name"=>'New Jersy', 'country_id'=>231],
            ['id'=>3955, "name"=>'New Mexico', 'country_id'=>231],
            ['id'=>3956, "name"=>'New York', 'country_id'=>231],
            ['id'=>3957, "name"=>'North Carolina', 'country_id'=>231],
            ['id'=>3958, "name"=>'North Dakota', 'country_id'=>231],
            ['id'=>3959, "name"=>'Ohio', 'country_id'=>231],
            ['id'=>3960, "name"=>'Oklahoma', 'country_id'=>231],
            ['id'=>3961, "name"=>'Ontario', 'country_id'=>231],
            ['id'=>3962, "name"=>'Oregon', 'country_id'=>231],
            ['id'=>3963, "name"=>'Pennsylvania', 'country_id'=>231],
            ['id'=>3964, "name"=>'Ramey', 'country_id'=>231],
            ['id'=>3965, "name"=>'Rhode Island', 'country_id'=>231],
            ['id'=>3966, "name"=>'South Carolina', 'country_id'=>231],
            ['id'=>3967, "name"=>'South Dakota', 'country_id'=>231],
            ['id'=>3968, "name"=>'Sublimity', 'country_id'=>231],
            ['id'=>3969, "name"=>'Tennessee', 'country_id'=>231],
            ['id'=>3970, "name"=>'Texas', 'country_id'=>231],
            ['id'=>3971, "name"=>'Trimble', 'country_id'=>231],
            ['id'=>3972, "name"=>'Utah', 'country_id'=>231],
            ['id'=>3973, "name"=>'Vermont', 'country_id'=>231],
            ['id'=>3974, "name"=>'Virginia', 'country_id'=>231],
            ['id'=>3975, "name"=>'Washington', 'country_id'=>231],
            ['id'=>3976, "name"=>'West Virginia', 'country_id'=>231],
            ['id'=>3977, "name"=>'Wisconsin', 'country_id'=>231],
            ['id'=>3978, "name"=>'Wyoming', 'country_id'=>231],
        ]);
    }
}
